spring.application.name=api_coding_challenge_book
server.port = 9000
spring.datasource.url=jdbc:mysql://localhost:3306/api_challenge
spring.datasource.username=root
spring.datasource.password=abcd@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=mysecretkeynotknownbyanyone54e6094ug846
jwt.expiration=3600000